" vim: ft=vim

runtime! archlinux.vim

filetype plugin indent on

syntax on

source $HOME/.vim/sources/set.vim

source $HOME/.vim/sources/keymap.vim

source $HOME/.vim/sources/plugin.vim

source $HOME/.vim/sources/color.vim

source $HOME/.vim/sources/func.vim

autocmd Filetype * set formatoptions-=ro

