if &compatible
  set nocompatible
endif

lua require('plugins')
lua require('myconf')
source $HOME/.vim/sources/set.vim
source $HOME/.vim/sources/statusline.vim
source $HOME/.vim/sources/keymap.vim
source $HOME/.vim/sources/func.vim

filetype plugin indent on
syntax on
