[editor]
clipboard = true

fontFamily = 'monospace'
fontsize = 10
linespace = 6

disableIMEinNormal = true
cursorBlink = true

[scrollBar]
visible = false

[sideBar]
visible = false
dropshadow = false

[dein]
tomlFile = '/home/nymphium/.config/nvim/dein.toml'
